<a href="https://colab.research.google.com/github/Luana957/Meus-projetos/blob/main/Aula2_Imers%C3%A3o_Alura_Ciencia_de_dados_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
df =pd.read_csv("https://raw.githubusercontent.com/guilhermeonrails/data-jobs/refs/heads/main/salaries.csv")

In [ ]:
df.isnull()

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...
133344,False,False,False,False,False,False,False,False,False,False,False
133345,False,False,False,False,False,False,False,False,False,False,False
133346,False,False,False,False,False,False,False,False,False,False,False
133347,False,False,False,False,False,False,False,False,False,False,False
133348,False,False,False,False,False,False,False,False,False,False,False

In [ ]:
df.head()

,work_year,experience_level,employment_type,job_title,salary,salary_currency,salary_in_usd,employee_residence,remote_ratio,company_location,company_size
0,2025.0,SE,FT,Solutions Engineer,214000,USD,214000,US,100,US,M
1,2025.0,SE,FT,Solutions Engineer,136000,USD,136000,US,100,US,M
2,2025.0,MI,FT,Data Engineer,158800,USD,158800,AU,0,AU,M
3,2025.0,MI,FT,Data Engineer,139200,USD,139200,AU,0,AU,M
4,2025.0,EN,FT,Data Engineer,90000,USD,90000,US,0,US,M

In [ ]:
df.isnull().sum()

work_year             10
experience_level       0
employment_type        0
job_title              0
salary                 0
salary_currency        0
salary_in_usd          0
employee_residence     0
remote_ratio           0
company_location       0
company_size           0
dtype: int64

In [ ]:
df['work_year'].unique()

array([2025.,   nan, 2024., 2022., 2023., 2020., 2021.])

In [ ]:
import numpy as np

#Criação de dataFrame de teste para usar como exemplo
df_salarios = pd.DataFrame({
    'nome': ['Ana', 'Bruno','Carlos', 'Diana', 'Eduardo'],
    'salario':[4000, np.nan, 3500, np.nan, 5000]
})

#Calcula a média salarial e substitui os nulos pela média e arredonda valores
df_salarios['salario_media'] = df_salarios['salario'].fillna(df_salarios['salario'].mean().round(2))


'''
Calcula a mediana salarial e substitui os nulos pela mediana
'''
df_salarios['salario_mediana'] = df_salarios['salario'].fillna(df_salarios['salario'].median())

df_salarios

      nome  salario  salario_media  salario_mediana
0      Ana   4000.0        4000.00           4000.0
1    Bruno      NaN        4166.67           4000.0
2   Carlos   3500.0        3500.00           3500.0
3    Diana      NaN        4166.67           4000.0
4  Eduardo   5000.0        5000.00           5000.0

In [ ]:
df_temperaturas = pd.DataFrame({
    "Dia":["Segunda", "Terça", "Quarta", "Quinta", "Sexta"],
    "Temperatura": [30, np.nan, np.nan, 28, 27]
})


df_temperaturas["Preenchido_ffill"] = df_temperaturas["Temperatura"].ffill()
df_temperaturas

       Dia  Temperatura  Preenchido_ffill
0  Segunda         30.0              30.0
1    Terça          NaN              30.0
2   Quarta          NaN              30.0
3   Quinta         28.0              28.0
4    Sexta         27.0              27.0

In [ ]:
df_temperaturas = pd.DataFrame({
    "Dia":["Segunda", "Terça", "Quarta", "Quinta", "Sexta"],
    "Temperatura": [30, np.nan, np.nan, 28, 27]
})


df_temperaturas["Preenchido_bfill"] = df_temperaturas["Temperatura"].bfill()
df_temperaturas

       Dia  Temperatura  Preenchido_bfill
0  Segunda         30.0              30.0
1    Terça          NaN              28.0
2   Quarta          NaN              28.0
3   Quinta         28.0              28.0
4    Sexta         27.0              27.0

In [ ]:
df_cidades = pd . DataFrame({
   'nome': ['Ana', 'Bruno','Carlos', 'Diana', 'Eduardo'],
   'cidades': ["São Paulo", np.nan, "Curutiba", np.nan, "Belém"]

})

df_cidades['cidades_preenchida'] = df_cidades["cidades"].fillna("Não informado")
df_cidades

NameError: name 'pd' is not defined

In [ ]:
,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,

In [ ]:
df_limpo.isnull().sum()

work_year             0
experience_level      0
employment_type       0
job_title             0
salary                0
salary_currency       0
salary_in_usd         0
employee_residence    0
remote_ratio          0
company_location      0
company_size          0
dtype: int64

In [ ]:
df_limpo.head()

NameError: name 'df_limpo' is not defined

In [ ]:
df_limpo.info()

<class 'pandas.core.frame.DataFrame'>
Index: 133339 entries, 0 to 133348
Data columns (total 11 columns):
 #   Column              Non-Null Count   Dtype
---  ------              --------------   -----
 0   work_year           133339 non-null  int64
 1   experience_level    133339 non-null  object
 2   employment_type     133339 non-null  object
 3   job_title           133339 non-null  object
 4   salary              133339 non-null  int64
 5   salary_currency     133339 non-null  object
 6   salary_in_usd       133339 non-null  int64
 7   employee_residence  133339 non-null  object
 8   remote_ratio        133339 non-null  int64
 9   company_location    133339 non-null  object
 10  company_size        133339 non-null  object
dtypes: int64(4), object(7)
memory usage: 12.2+ MB

In [ ]:
df_limpo = df_limpo.assign(work_year= df_limpo['work_year'].astype('int64'))

NameError: name 'df_limpo' is not defined

In [ ]:
#Aula 3 aqui

In [ ]:
df_limpo.head()

NameError: name 'df_limpo' is not defined